# Generated by Django 2.2.3 on 2019-08-09 07:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('phone_number', models.CharField(max_length=14)),
                ('email', models.EmailField(max_length=30)),
                ('location', models.CharField(blank=True, max_length=20, null=True)),
                ('role', models.CharField(choices=[('ADMIN', 'Administrator'), ('CUSTOMER', 'Customer'), ('EMPLOYEE', 'Employee')], default='ADMIN', max_length=10)),
                ('user_name', models.CharField(max_length=10)),
                ('password', models.CharField(max_length=15)),
                ('company_name', models.CharField(blank=True, max_length=15, null=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Api.Project')),
            ],
        ),
        migrations.CreateModel(
            name='Issue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issue_name', models.CharField(default='issue', max_length=50)),
                ('issue_description', models.CharField(blank=True, max_length=40, null=True)),
                ('attachments', models.FileField(blank=True, null=True, upload_to='uploads/')),
                ('status', models.CharField(choices=[('NEW', 'new'), ('PENDING', 'pending'), ('RESOLVED', 'resolved')], default='NEW', max_length=10)),
                ('date', models.DateTimeField(auto_now=True)),
                ('priority', models.CharField(choices=[('HIGH', 'high'), ('LOW', 'low'), ('MODERATE', 'moderate')], default='MODERATE', max_length=8)),
                ('issue_assignee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assigned_user', to='Api.User')),
                ('issue_submitter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='issue_submit', to='Api.User')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Api.Project')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CommentBody', models.CharField(blank=True, max_length=40, null=True)),
                ('issue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='issue_comment', to='Api.Issue')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Api.User')),
            ],
        ),
    ]
