# Generated by Django 2.2.3 on 2019-08-07 02:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('phone_number', models.CharField(max_length=14)),
                ('email', models.EmailField(max_length=30)),
                ('location', models.CharField(max_length=20)),
                ('role', models.CharField(choices=[('ADMIN', 'Administrator'), ('CUST', 'Customer'), ('EMPLOY', 'Employee')], default='ADMIN', max_length=6)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Api.Project')),
            ],
        ),
        migrations.CreateModel(
            name='Issue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issue_name', models.CharField(default='issue', max_length=50)),
                ('issue_description', models.CharField(max_length=40)),
                ('attachments', models.FileField(upload_to='uploads/')),
                ('status', models.CharField(choices=[('OPEN', 'open'), ('PROGRESS', 'progress'), ('CLOSED', 'closed')], default='OPEN', max_length=6)),
                ('date', models.DateTimeField(auto_now=True)),
                ('priority', models.CharField(choices=[('HIGH', 'high'), ('LOW', 'low'), ('MODERATE', 'moderate')], default='MODERATE', max_length=8)),
                ('issue_submitter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Api.User')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Api.Project')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CommentBody', models.CharField(max_length=40)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Api.User')),
            ],
        ),
    ]
